apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy: {}
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 2004
        runAsGroup: 2000
      initContainers:
        - image: busybox:1.38.0
          name: permissions
          command: ["sh", "-c", "chown 2004:2000 /run"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: run
              mountPath: /run
      containers:
        - image: lscr.io/linuxserver/sonarr:4.0.19.2979-ls322
          name: sonarr
          ports:
            - containerPort: 8989
          resources: {}
          envFrom:
            - configMapRef:
                name: media-permissions
          env:
            - name: PUID
              value: "2004"
          volumeMounts:
            - name: run
              mountPath: /run
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: run
          emptyDir:
            sizeLimit: 500Mi
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
