apiVersion: v1
kind: Secret
metadata:
  name: firefly-secrets
data:
  APP_KEY: OVFRTjNmS3MxbEpvMllUOWR4T3puRmdhQmNHc3ZGRjc=
  DB_FIREFLY_USER_PASSWORD: WTkzVnQ2QkROTzMxN1hackh1TW1MVmRiQmpGMzZrMiZDeG9xbEtJVE4jeG9Wbkt5WnE=
