apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana
#  - kube-prometheus-stack
  - kube-state-metrics
  - prometheus-node-exporter
#  - victoria-metrics-cluster
#  - victoria-metrics-agent
#  - victoria-metrics-k8s-stack
  - victoria-metrics-single
