apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
data:
    RENOVATE_SECRETS: ENC[AES256_GCM,data:pd33FWt9+A1o4H5ZNvvxBWUTfIoLL52s1WvL6QHS9zA3gDBOHyajrfp0Vsx8QZRpbOD+lD2F2mGz/h1K7I+/V2EVUmgPbqg5Ge6ePw==,iv:TGgH+63AQeH+NN+D4C9JFO2bO/3v0uL/ews+I1yL7KQ=,tag:jcVxwN1hmhakT8fClX0fXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWUNVWlF5RzlSZ0xkYU92
            dThSU3JnVENldkFkbHJ5d2o1SEtkV1RjK2ljCnBDT0hhZDJVaitaNFRMbHZHVDdq
            YnUvUHRvWk9wN1JhL2VGNEJyelRuOW8KLS0tIHkvMjdjbzI0cldCY3pFOExHV0F1
            VTdtMlhnVEZvbTRZbnZYQ1I2SkNRREUKh6nH3cc5dryZwPVh6srQdBjI7EnF3Uft
            rVDr6HBSSrX5rhyDaCNIE11lPXDCP97KkKM8lbXCO9WfH+Cr04qLRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T17:25:54Z"
    mac: ENC[AES256_GCM,data:xQOqZZtCm3Ww+Z3W4tmL7HEO0GHboS2Zko8k9XjsLDKDk0EQdHMbOV4qqgPzz67lln/bYfoUlbJeAO3bXnTE8SMJ4XbgvTHkNRlb18y9cFe534rwGkSp+IRY3DcLiNtxfMj81gcRkIR8rYezpvUWuhedPriIhbDcXbpLTHj5LhE=,iv:/hOmIltzJi8ELx2MQdJnA1o4d93FKWjhrjbQRAJgV/w=,tag:5dxc//3OjYaZV6IymgBXnA==,type:str]
    version: 3.13.2
