apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
data:
    RENOVATE_SECRETS: ENC[AES256_GCM,data:4ofGdQBXKpLcjSahxA76MVUPMWCnPzz6V4X+1XPOr0fUscG+7QhuRiIr2fa9hexO8gp/nsCmPEY2Xm4h5B+mpn30kVPoTtzBY96Oyg==,iv:oikiKh+upOn1DQEfs8SE/li/ymLERjTazEOg2VQA/uw=,tag:7ofkXcktUg2KYTM/8F5eYA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:fnlv78/WyTvCxx7Ab/jr9xabTBMFdUhtnBZPYV6bmZA9kMF/VsESqlW6t57DuV1Ainlxl8NaRvM=,iv:PkAW8pynjjijDrz8yT2lIrfABB1eB71qGd2UYwwzyMo=,tag:gdyo0Q8wIEav5lVglU3xWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUGd4aVdaYlViSDE0SFU3
            dThXbE5ZZGR6M1RjTmoySXhsM1dLRjJkM2t3CndBcTNTc2tzTnRobUZra1l2MjRm
            ck1rMXVFMXFqUmVuTzRLSFlhVFBCRkUKLS0tIDFHKzVhbDY0UDlSYldzQjVzcVFu
            dHdXT0JsOFg2TnMxNnhFTjJFNSt6YkkKAdXUAaDH2ZMVkAnBKfQGyaNQxvh2q+Me
            Q5wk+ukRlkPMZXNPcMOLkxKaM/T+gf/5ma0zuUwJlbQm7kGIdknbuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T17:33:33Z"
    mac: ENC[AES256_GCM,data:IgYEE2cj6CX6aZH5bkX2ILW0MEy1ccf94KgbfFANeBDxja46gOJUXREgn91hML0z7IuDB/k++RnVAgzLnX/eyp3wNh/pRd6etbZje9lEeR3flROU9w/D6g7CJNBVZtUZRIKdpGO4Bvb1mJA04N6bnEikdEspkaECI5tuuJ8aJfY=,iv:cWOHomAYZsq3rRxzVjaeu/40GZeJa8tY31DBs/xb/Hg=,tag:LkPs6BzQLBn8Z/zmWkSJ1w==,type:str]
    version: 3.13.2
