apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DYEmKO934F4V81Xjfp6drCM3vsi477cMc+wsWH4bqZKOhjwaFTzPaPitLWpJFIWTID9sI2PXNnE=,iv:7MdX/U7nafa/BzYsBHRXfieS9LX6t2K5WUsCod1o4ro=,tag:5AS0N2Evu//X7qN949z1hg==,type:str]
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aHJOMHJhN3d0bXUyWlli
            YXZKNHJJK2ZZUUxtaVVuZFozRlp6UjNEWkNRCnVWeS80SXNidnZMeWd5b1BDU2Zr
            MitBUklUa1pyMXJaY1lXYjN4cGI0NGsKLS0tIHJLTDFRNEltamNTVXVld3BIK3Fx
            clBVeU1mV0Q2NFdpejhvUU02MmhLNmMKdPe8GAE988M4n0XwVThsbwvdNvAR8iaR
            aDLapPvBFtyS0/eZVw/OABqpu7VA4OU/mxRIWJVSmLBT92LmJfw+ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T19:32:06Z"
    mac: ENC[AES256_GCM,data:HSHq3p0XuVeXPnZbpneYBuLBIsSvTVeTyon1yefpM4CuXAP46Mob86TMPvmyohmxo5j4vLDn1peNhrg+ncM6AbNTZOJ8Asxcr49bOWWirjacQJU59Ti5+Y6DONIfTdDQrxFAKd77dlYvxwfLqLRWVOWNZXw54vLXqIOi09tUUY4=,iv:9A11bhw/9wEGFnn43VJftN15Ae9/SUr+14u8qCvc5Eo=,tag:1tXeHbn375jZ/qlKz9cHOg==,type:str]
    version: 3.13.2
