apiVersion: batch/v1
kind: Job
metadata:
  name: firefly-db-setup
  namespace: firefly
spec:
  completions: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: firefly-db-setup
          image: mariadb:12.2.2
          command: ["/bin/bash", "/scripts/db-setup.sh"]
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-root-credentials
                  key: MARIADB_ROOT_PASSWORD
            - name: DB_FIREFLY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: DB_FIREFLY_USER_PASSWORD
          volumeMounts:
            - mountPath: /scripts
              name: db-setup-script
      volumes:
        - name: db-setup-script
          configMap:
            name: firefly-db-setup-script
