apiVersion: v1
kind: Secret
metadata:
    name: mariadb-root
data:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:z5Zur3QZtSYEabIYBV1TVlSmZ01/lAiEP4zuKDX7f4zPHDB+ROs248UTCNr5173yrAduELBuSNM5NnEtozAFvsXhKfw=,iv:JLV1SjKFYkquS2gHgtZAZ6uxP0bVtP5f78pAFS6kHWE=,tag:H+9DKfsnYXe9Dd0Ma4V/Iw==,type:str]
sops:
    age:
        - recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTmNCWWpqNTB1Ky80V3VU
            eVhqZStUeVhSWElueVR4S2llVXhHRHR6dkg4CitRa05OVDlZaEphWTV0TkJaWTJn
            SllPbTBLYXRzVlQrcFZpRXoyS0FvK1kKLS0tIDVaRWcrNWFOdkJWMXZaUng5bjRY
            T082YlRDNzd0R2d1UUtpWms5eVovYWMKEMOmb9xaLwnPIcMisbOEQFav9TOmqbBH
            AjW+CeOrDWwwwFE5pNV7HTB9ukWNos6ttoaFAyn8et3ttO7R5lXUuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T23:50:07Z"
    mac: ENC[AES256_GCM,data:Xzp1W2R02MvS0+z6Aa6tf3fp/zDX4MbuOnu2NrF1RrbIsK55yj/lRcf8D6FkrJMFz4m7/dGIVb7wGgv18bc9kmqFL7W3pDbsi/Stg0KYYetZjJpLDEb1tSime/9oqyn6n7rJx1eSPjP+VxDbeYrVxuIaAFRE1gCITWFTQpNYxJI=,iv:FSXZTrqXtQ9ixPOHxvVF0JEBzVIeHj5A3qBkdQSOmxg=,tag:KgTzGfpR+/oVuzQj5ESghw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
