apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb-headless-svc
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 999  # mysql group ID
        runAsUser: 999  # mysql user ID
        runAsGroup: 999  # mysql group ID
      containers:
        - name: mariadb
          image: mariadb:12.2.2
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-pvc
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mariadb-root
          securityContext:
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
    - metadata:
        name: mariadb-pvc
        namespace: mariadb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path-retain
        resources:
          requests:
            storage: 5Gi
