apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb-headless-svc
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: mariadb
          image: mariadb:12.1.2
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-pvc
              mountPath: /var/lib/mysql
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root
                  key: MARIADB_ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mariadb-pvc
        namespace: mariadb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path-retain
        resources:
          requests:
            storage: 5Gi
