apiVersion: v1
kind: Secret
metadata:
    name: homepage-auth-secret
    namespace: homepage
data:
    HOMEPAGE_AUTH_PASSWORD: ENC[AES256_GCM,data:OkYMf1NR9aRVDvA/KNJhrbpha81MqPqu9f2ffIiliI8iGQZ79XTFjd0KH7c=,iv:CV1pDh9LuoecgoNZXdW2HMw+UxtAXaDv+9Z4q2ecT5w=,tag:NJsXFAMIEVR54M6Lluv6ZQ==,type:str]
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:s8ifCjWCs51KDS/XXPaWKVM1/mKrQzgF13CYkJwGMU/WZVOce06iJGicFDy4d20mYvVZPbJRI5Rgqicu,iv:0UknnHIEyj1rNuYXbcwuykPSadYoEr2lHqfZkCZU/xM=,tag:d2edu5HVK/45P9O64EP2Xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWlI3NmNiQWZ4VUxtbnpu
            LzBGbFRSUWFBK1h6M1ZUU0NNa0FjTElmeEJrClRRUjJlWnRIOVd3Tm5NZSs3RGlE
            TmJ3RjZodjVBL25aeUY4blZ3M293N3cKLS0tIG45TTExWGpycEw3dFltbCtaZHM4
            c2RhZHB3RzdwVE9SUEdGMlJqM0tSZ2sKPMxuIlLPUrhf4xMheJJ3OlWuetOdTlqY
            sljNUFMiTt3gpomFpYqNNL/BbmjYCnJA8Kr0lvYFiROIyaiscZ3dAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:57:53Z"
    mac: ENC[AES256_GCM,data:YGc0X9FLbUOfNNuNxf4A49RvSO8/EHD1eWjnORPBR4Kx964Ya9AMTAsemhwQ/L3m4AbCLAaeaQjoBvkJ0EGJTV0N5pdyhD5pWENDLuUpHd3oZZaTjhAr6FfJuhdTcT8NEDA8CKDZMKafE13BXdNgFOcWq8nwBJ+9if3AzlqK4Kw=,iv:6JC9FK8NdLXdB027CGwcHQ+J6RMya4V7mcfQ5CriZBE=,tag:KJhOlPdjjAyZRBnryZm98g==,type:str]
    version: 3.13.2
