apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: homepage
data:
    token: ENC[AES256_GCM,data:VroE+QWx/w9JMAGmDDvXL6s4O231u2oJLRHBeqE6f4ICcbf4BmreEPHCTUFkhNq6KAs4z1dClVWK1OJAlmC7jINuCzfAPnSZV4RwPcreb7zql56xiECTILr5REq1ShWbHNJOxqLODD7y8C9shHV/WCXXNJ3gs7+LzxKj/G2glXtZqrJdMGFwSFpQjxXGHuqPFsKLu4O1Eji3kouPCeo5G4X3ldil9fplO+kXbF69HnW23rbOC8gQ/ybEYcebukvAEyccqkaJEN/N5i/Gp+ZxYHFUyzk/Q+urXj2+LdC+TX0c8lIUHWunf3DfoZblErmCq9yPvZvYNBY=,iv:+C/IduJGnNX5TKcNTojGQfKhz7K/y9qfLndda0zMxNg=,tag:NnMozkZUMlTaj98IECVhHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SVRsOUlTQktLVlczYW90
            OXZoUDczZE5YaGRyOWZCL3d6Y3EwYkxCc1FzCkN6SWZCUWhTdDU4Rm4yMG1ZTTRW
            d3hCOEZjNGltcUR6dWRBYzhZZ09NSHMKLS0tIGlVNHdUKzF1KzdoN054T0lOMjl3
            T0NyUnJaNjZneStUM1AvVk50a2FwUjAKlyuBKupxOlNSMQHPUnfXJtLvBFpvctx+
            pFcygvx24vifX2XNNx41lFEgdbB3TnTJ+k9vkPJ7qMyqVzOCk/iGZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:08:46Z"
    mac: ENC[AES256_GCM,data:20p/VkuO0iHrPT0r36zvApNYvPV4xvvpQcsqp+rfe6K7E0/AFRcEo3UghtH9es2J3ou4erR9aWAiu4w+7MhpCtfHri2XEXU4vMwBxfcg2HbPwIjXq48dEgXCVWi2MPnTzjd3+ROBcdMLg7Dq+z7lxUnXVmfmfHa7JfQTbB11b6M=,iv:m3JCmNADXltFS5KAz8yoFjESePm/vaul5bYuM8CnJqM=,tag:mJuRQx5AX6jRjlBBWxqyfg==,type:str]
    version: 3.13.2
