apiVersion: v1
kind: Secret
metadata:
    name: homepage-auth-secret
    namespace: homepage
data:
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:ZydrCS4WjeulPkNO5quV//D2vqDUCbx7M5f0SBj/86XnnKPIrGzzD+Dr4Oz7zUWAmJig9D7YYNZh73a0,iv:67BH9TIIsK5xcksubnkmodxUDY1J+bSaSSWk4URZcHw=,tag:OWlEz/wlHi5gUjHxNDm/Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2STRMdU5EMHB5ZFFmbkVC
            VEZqbkk4TUk0Z2VTM3JGVThtMml4SEo4MlYwCi9UOW9vM09HOHh5cEJNMTJtNkZu
            SVB4ZXhCTGI1N1dURTJiTVM1THNTMlkKLS0tIGVrNUo0WGxTaDBtOTZsWm8ycTlH
            b1Fna0llcFRzUFM2OGx4SWs3MnR1cFEKQpwMXcYY1AmNh2dowAbdLgpF32Dkyp8g
            5lIpKzYKbVFE85Xwrs3LaKy1zvqg7RlroLC5S3PgnWy1yLB/cA0hYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T20:57:55Z"
    mac: ENC[AES256_GCM,data:ccq2RQb8t9ic6uoK9HCJMk9d7gGmd5mRDnRSUjr1y0fpDpeIDIw9g6xzoeFYeQu2WD4guYb1V4zV2y7xRr0MnKMbDWFhRCzgrlWmxKQ7aIud6a6+w4USb0bkR88z+PETpysG6r53KjuFLF30eEWIPjT4zGTuMS0OT7Bb5T7jHMY=,iv:h7Oe7F6ustKPTIWbYMxZyiU3ltSVR6WVqb9LNAkG38s=,tag:jEnn85ZY2YnxAiF9zzo4Rg==,type:str]
    version: 3.13.2
