apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - cloudflared.yaml
  - namespace.yaml
  - pvc-data.yaml

configMapGenerator:
  - name: media-permissions
    literals:
      - PGID=2000
      - UMASK=002
    options:
      disableNameSuffixHash: true
