apiVersion: v1
kind: Secret
metadata:
    name: mariadb-root
data:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:jD1fviZT78dmRl0lmOJcZFFZCD5HCrwjHNwy0WuggmbXek6DzAVPjRX8VWuZ+7eQotPBrDP9XpcadqY5Jpj3og==,iv:zfd7QleSsjkR2Qg/BHZ7uGbrgmQKLzAwrZoZ2BzvUME=,tag:cvI+ibbOdWdk/4Du/JFcIA==,type:str]
sops:
    age:
        - recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UndwVGZUMEl6b2RzQWJo
            R2xpZXpxK3hzMmVqY1FoYldtODZFbHBXcVdjCk1xOWtCZ0RoTDVsN2VncFVxRktB
            UFBrcHhZRjVRWmkzTVF0NkQyTDFBbjAKLS0tIGJ6SGdIRXdtUHI2RW9BRVJyRWFl
            RnBRdzNCRWFpNGc3a3JQWDZkL2dHc1EKqyf4tJANU+0dsYCTZdK1Viu1kBS51zkD
            gYAOsJFtV4iNhfmi5c4qwO+iz23KtEQK6vNQuIgNevqkjHOkyJ8O0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T00:59:55Z"
    mac: ENC[AES256_GCM,data:5JzmmEOTUiCKAOwrRC4fdS1CLQObIgI4gS+97KshpsMKhfsvQBWQsz8EvW8VHMDi6KXa3rNYAfxko4WbQIsgKAkMUFSAO+aHhU2MSNpz+7FQktQFff6QtRhCXH36D1DFK4bU3YobSgTv64kNvXBZ9Skenwa5kNy6T3QrkD7TbPI=,iv:yoRBJx34lPmZwGVZaiO6nl4astK844SCPPO0zAbEqzI=,tag:GmW3CKEY0zhfGKc9fgYIyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
