apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:wCILSTgsWvtX4iDdBzV8zsaj9jgbbUoQoFs1DSz6vkLTU/6iwmRLwC+pbQP1yDO2JmGf9HR7J3k=,iv:HwkNKAHLPlD97zAHUCnyRPlkVjcAIjRDLTE1G5bjTX8=,tag:wSYgf8AS6pXu2awUU5ZpMQ==,type:str]
kind: Secret
metadata:
    name: renovate-env
sops:
    age:
        - recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMzBDdXo5d1BxeWJvcXJC
            bzJqUjdxeU5tdGRjSERWU2lkUWo5amhKT1dRCkNOYW9LMzFQMmc0dlNreUc4QSsw
            MFMzMGkyd25LazNPQzBlSmpGRGJ1S28KLS0tIG5CSkRvckdqdTF0dkY0cDJzTWtZ
            dGV3aklPZDZpdW8yd2s5dEhJQk1kNkUKK03/2du7WwA0d+ijEFeM/TLbBLYHz4b0
            YZHYM0WUYY+bcof6IDzKHflYH0L/FQcXGnPrWPSPScBxkVQVt/YNcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T20:12:27Z"
    mac: ENC[AES256_GCM,data:FHC8DySIVjYGTMFyIou6ImMjQkPrTL8Zw+OlfGonydAOEnTdXvVmHvstCcmN3CIr6/P9qVoUEuSksic9NFjbYIRI73cyuGL40q6ejVc5jXvkQUANlep7hWTcPbVTwxHwmrnLz0uo0gaZKJr2j1LCYrmYoWwT+W0XJ1udcx9mlNw=,iv:p39GK2eC+MPEk7bmwLzl5OV80M9f+22H3YwJw58SF58=,tag:pj66bwgBXj9IFJo0ZvOPfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
